services:
  filebrowser:
    build: .
    container_name: filebrowser
    ports:
      - "${FILEBROWSER_PORT:-50000}:80"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - USERNAME=${INITIAL_USERNAME:-admin}
      - PASSWORD=${INITIAL_PASSWORD:-password}
      - FB_DISABLE_EXEC=${FB_DISABLE_EXEC:-false}
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    restart: unless-stopped